<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="me604" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
 <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.05" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.1" /> <!-- Link 0 -->
  <xacro:property name="length1" value="0.6" /> <!-- Link 2 -->
  <xacro:property name="length2" value="0.6" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->

  <xacro:include filename="$(find arm_description)/urdf/arm.gazebo" />
  <xacro:include filename="$(find arm_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find arm_description)/urdf/link.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link0"/>
  </joint>
    
  <!-- Base Link -->
  <xacro:link0 name="link0" height1="${height1}" width="${width}" mass="${mass/6}" />
  <!-- Links of the manipulator -->
  <xacro:link_arm name="link1" length="${length1}" width="${width}" mass="${mass}"/>
  <xacro:link_arm name="link2" length="${length2}" width="${width}" mass="${mass}"/>
  <!-- laser scan link -->
  <xacro:link0 name="hokuyo_link" height1="${height1/2}" width="${width}" mass="${mass/12}" />

  <!-- Joints of the manipulator -->
  <joint name="joint1" type="continuous">
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 ${height1 +0.03}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

   <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${length1 - 0.05} ${width+0.01}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 0 1" />
    <parent link="link2" />
    <child link="hokuyo_link" />
    <origin xyz="0 ${length2} ${width/2}" rpy="0 0 0" />
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>