<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="me604" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1"      /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.05"  /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.5" /> <!-- Link 0 -->
  <xacro:property name="length1" value="1" /> <!-- Link 1 -->
  <xacro:property name="length2" value="1" /> <!-- Link 2s -->

  <xacro:include filename="$(find arm_description)/urdf/arm.gazebo" />
  <xacro:include filename="$(find arm_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find arm_description)/urdf/link.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link0"/>
  </joint>
    
  <!-- Base Link -->
  <xacro:link0 name="link0" height1="${height1}" width="${width}" mass="${mass/6}"/>
  <!-- Links of the manipulator -->
  <xacro:link_arm name="link1" length="${length1}" width="${width}" mass="${mass}"/>
  <xacro:link_arm name="link2" length="${length2}" width="${width}" mass="${mass}"/>
 
  <!-- Joints of the manipulator -->
  <joint name="joint1" type="continuous">
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 ${height1 +0.03}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

   <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${length1 - 0.025} ${-width-0.01}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <joint name="hokuyo_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.0 ${height1 + width +0.1}"/>
    <parent link="link0"/>
    <child link="hokuyo_link"/>
  </joint>



  <link name="hokuyo_link">
    <inertial>
      <mass value="0.270"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="2.632e-4" ixy="0" ixz="0" iyy="2.632e-4" iyz="0" izz="1.62e-4"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://hector_sensors_description/meshes/hokuyo_utm30lx/hokuyo_utm_30lx.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.0115"/>
      <geometry>
        <box size="0.058 0.058 0.087"/>
      </geometry>
    </collision>
  </link>
  
</robot>